
// HIP AND SHOULDER MOVEMENT DRILL
// IMPORTANT MOVEMENT DRILLS FOR BJJ
// GUARD RETENTION FUNDAMENTALS
// THE GUARD POSITION
SCISSOR SWEEP TO MOUNTED CROSS CHOKE
// ROCKING CHAIR DRILL
NO GI SCISSOR SWEEP
// ROCKING CHAIR PARTNER DRILL
SCISSOR SWEEP TO ARMLOCK COMBINATION
SIT UP SWEEP TO TRIANGLE CHOKE
SIT UP SWEEP TO KIMURA FROM GUARD
GUILLOTINE FROM THE CLOSED GUARD IN BJJ
CROSS CHOKE FROM CLOSED GUARD
BASIC ARMLOCK FROM THE CLOSED GUARD
CROSS CHOKE VARIATION FROM CLOSED GUARD
ARMLOCK VARIATION FROM THE CLOSED GUARD
CROSS CHOKE USING AN OVER THE BACK GRIP FROM GUARD
LOOP CHOKE TO SWEEP COMBO FROM CLOSED GUARD
TRIANGLE DETAILS
// KIMURA ATTACK DRILL
ARM DRAG BACK TAKE FROM GUARD
RUBBER GUARD ARMLOCK SETUP
RUBBER GUARD PUMMELING AND SEQUENCE
TRIANGLE CHOKE OFF RUBBER GUARD SEQUENCE
OMOPLATA OFF OF RUBBER GUARD SETUP
SPIDER GUARD BASIC CONCEPTS
SPIDER GUARD GRIPPING
STANDING TRIANGLE FROM SPIDER GUARD
SIMPLE REVERSAL FROM BUTTERFLY GUARD
DLR ( DE LA RIVA) BASIC STAND UP SWEEP
DLR (DE LA RIVA) SPIN UNDER SWEEP
DLR (DE LA RIVA) BASIC SIT UP SWEEP
DLR (DE LA RIVA) OVERHEAD SWEEP
CROSS CHOKE FROM BUTTERFLY GUARD
HOOK SWEEP OFF WRIST CONTROLFREE
HOOK SWEEP USING DOUBLE UNDERHOOK CONTROLS
HOOK SWEEP USING THE GABLE GRIP TO TRAP HEAD
ARM DRAG SWEEP
SPIDER GUARD BASIC MOVEMENT AND GRIPPING
SPIDER GUARD TO ARMLOCK
LEG LASO TO TRIANGLE CHOKE
TRIANGLE CHOKE FROM SPIDER GUARD
KNEE SLICE COUNTER TO TRIPOD SWEEP
BEAR HUG PASS DEFENSE
COLLAR DRAG COUNTER TO TOREANDO GUARD PASS IN BJJ
KNEE SLICE COUNTER TO X GUARD IN BJJ
OVER UNDER COUNTER USING OVERHEAD SWEEP
WRIST LOCK COUNTER TO THE POPULAR OVER/UNDER GUARD PASS IN JIU JITSU
COUNTER TO THE LEG WEAVE GUARD PASS IN JIU JITSU

// FROM Closed Guard
// UP AND OVER SWEEP FROM CLOSED GUARD (Hip Bump)
LUMBERJACK SWEEP FROM CLOSED GUARD
ARM DRAG TO ARMLOCK SERIES FROM CLOSED GUARD
LOOP CHOKE FROM THE CLOSED GUARD
OVER HEAD SWEEP FROM CLOSED GUARD

// 
// - - - VIDEOS TO WATCH - - -
// 

//  - Back Attacks 7: The Most Powerful Chokes from the Back Position
// (https://www.youtube.com/watch?v=EQ51_TcXHQY)

// 
// - - - MOVES TO GOOGLE - - -
// 

// - Position Variations

// Weakside?
// Strongside?

// - Grips

// Kimura Grip
// Double Wrist (Double Motorcycle)
// Claw Ride
// Half Nelson


// - SUBMISSIONS

// Bow and Arrow Choke